# -*- coding: utf-8 -*-
"""sentiment_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U9Qph_Q1RNSvgPNC8uzi6emlO3mBOi4z
"""

import pandas as pd
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

#Load the original data

df = pd.read_csv("customer_reviews.csv")
print("Original Data")
print(df.head())

#Binary Sentiment Analysis

sentiment_model = pipeline("sentiment-analysis", model="distilbert-base-uncased-finetuned-sst-2-english")
reviews = df["review"].astype(str).tolist()
sentiment_results = sentiment_model(reviews)
df["sentiment"] = [result["label"] for result in sentiment_results]

#Emotion Classification

emotion_model = pipeline("text-classification", model="j-hartmann/emotion-english-distilroberta-base")
emotion_results = emotion_model(reviews)
df["emotion"] = [result["label"] for result in emotion_results]

#Direct Tokenizer + Model approach for Summarization

model_name = "facebook/bart-large-cnn"
sum_tokenizer = AutoTokenizer.from_pretrained(model_name)
sum_model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

summaries = []
for review in reviews:
    # Summarize only long reviews
    if len(review.split()) > 30:
        # Tokenize the text block
        inputs = sum_tokenizer(review, max_length=1024, truncation=True, return_tensors="pt")
        # Generate summary IDs
        summary_ids = sum_model.generate(inputs["input_ids"], max_length=25, min_length=5, do_sample=False)
        # Decode back into a raw string
        summary_text = sum_tokenizer.decode(summary_ids[0], skip_special_tokens=True)
        summaries.append(summary_text)
    else:
        summaries.append("Short review - no summary needed")

df["summary"] = summaries

# 5. Print Distributions and Save
print("\nSentiment Distribution")
print(df["sentiment"].value_counts())

print("\nEmotion Distribution")
print(df["emotion"].value_counts())

df.to_csv("analyzed_reviews.csv", index=False)
print("\nSaved: analyzed_reviews.csv")

print("\nFinal Data")
print(df.head())

